apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mhr-replication
  labels:
    app: mhr-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mhr-nginx
  template:
    metadata:
      labels:
        app: mhr-nginx
    spec:
      containers:
      - name: mhr-nginx-container
        image: nginx
